"""
docx_export.py
Generates a downloadable DOCX meeting-minutes document from a
meeting_data dict (as returned by Meeting.to_dict(include_full_result=True)).

Expected input shape (see models.py / pipeline_runner.py):
{
    "meeting_title": str,
    "created_at": str (ISO date, optional),
    "transcript": str,
    "highlights": [str, ...],
    "chapters": [{"chapter_id", "title", "summary", "text"}, ...],
    "action_items": [{"text", "task" (optional), "assigned_to", "due_date", "method"}, ...],
}
"""
import io
from datetime import datetime

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _format_date(iso_str):
    if not iso_str:
        return "N/A"
    try:
        dt = datetime.fromisoformat(iso_str)
        return dt.strftime("%B %d, %Y")
    except (ValueError, TypeError):
        return iso_str


def generate_docx(meeting_data: dict) -> bytes:
    doc = Document()

    title = meeting_data.get("meeting_title") or "Untitled Meeting"
    created_at = _format_date(meeting_data.get("created_at"))

    # --- Title block ---
    doc.add_heading("Meeting Minutes", level=0)
    doc.add_heading(title, level=1)

    # --- Metadata table ---
    # Note: only Date + Generated-by are populated — the Meeting model has no
    # time-range or participants fields yet. Add rows here if those get added.
    meta_table = doc.add_table(rows=0, cols=2)
    meta_table.style = "Light Grid Accent 1"
    for label, value in [
        ("Date", created_at),
        ("Generated by", "AI Meeting Minutes Generator"),
    ]:
        row = meta_table.add_row().cells
        row[0].text = label
        row[0].paragraphs[0].runs[0].bold = True
        row[1].text = value

    doc.add_paragraph()

    # --- Highlights ---
    doc.add_heading("Highlights", level=1)
    doc.add_heading("Key Points", level=2)
    highlights = meeting_data.get("highlights") or []
    if highlights:
        for point in highlights:
            doc.add_paragraph(point, style="List Bullet")
    else:
        doc.add_paragraph("No key points detected.")

    doc.add_heading("Action Items", level=2)
    action_items = meeting_data.get("action_items") or []
    if action_items:
        ai_table = doc.add_table(rows=1, cols=3)
        ai_table.style = "Light Grid Accent 1"
        hdr = ai_table.rows[0].cells
        hdr[0].text = "Task"
        hdr[1].text = "Assigned To"
        hdr[2].text = "Due Date"
        for cell in hdr:
            cell.paragraphs[0].runs[0].bold = True
        for item in action_items:
            row = ai_table.add_row().cells
            text = item.get("text", "")
            task = item.get("task")
            row[0].text = task if task and task != text else text
            if task and task != text:
                quote = row[0].add_paragraph().add_run(f"\u201c{text}\u201d")
                quote.italic = True
                quote.font.size = Pt(8)
                quote.font.color.rgb = RGBColor(0x77, 0x77, 0x77)
            row[1].text = item.get("assigned_to") or "Unassigned"
            row[2].text = item.get("due_date") or "No due date"
    else:
        doc.add_paragraph("No action items detected.")

    doc.add_paragraph()

    # --- Detailed Minutes (chapters) ---
    doc.add_heading("Detailed Minutes", level=1)
    chapters = meeting_data.get("chapters") or []
    if chapters:
        for i, chapter in enumerate(chapters, start=1):
            chapter_title = chapter.get("title") or f"Topic {i}"
            doc.add_heading(f"Chapter {i}: {chapter_title}", level=2)
            doc.add_paragraph(chapter.get("summary", ""))
    else:
        doc.add_paragraph("No chapters available.")

    # --- Footer ---
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run(
        f"Generated automatically by AI Meeting Minutes Generator — {created_at}"
    )
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
