"""
pdf_export.py
Generates a downloadable PDF meeting-minutes document from a
meeting_data dict (same shape as docx_export.py expects).

Renders an HTML template and converts it to PDF via WeasyPrint, so the
PDF and DOCX outputs stay visually consistent with each other.
"""
from datetime import datetime

from weasyprint import HTML


def _format_date(iso_str):
    if not iso_str:
        return "N/A"
    try:
        dt = datetime.fromisoformat(iso_str)
        return dt.strftime("%B %d, %Y")
    except (ValueError, TypeError):
        return iso_str


def _esc(text):
    """Minimal HTML escaping — chapter/highlight/action-item text comes
    from model output, not from a trusted template, so escape it."""
    if text is None:
        return ""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


_CSS = """
    @page { size: A4; margin: 2.2cm; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #222; font-size: 11pt; line-height: 1.45; }
    h1 { font-size: 22pt; margin-bottom: 0; }
    h2.subtitle { font-size: 15pt; color: #444; margin-top: 2px; font-weight: normal; }
    h2 { font-size: 14pt; margin-top: 28px; border-bottom: 2px solid #333; padding-bottom: 4px; }
    h3 { font-size: 12pt; margin-top: 18px; color: #333; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0 20px; }
    table.meta td { border: 1px solid #ccc; padding: 6px 10px; }
    table.meta td:first-child { font-weight: bold; width: 25%; background: #f5f5f5; }
    table.actions th, table.actions td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; }
    table.actions th { background: #f5f5f5; }
    ul.bullets { padding-left: 20px; }
    ul.bullets li { margin-bottom: 6px; }
    .chapter { margin-bottom: 16px; }
    .footer { margin-top: 40px; text-align: center; font-size: 9pt; color: #666; font-style: italic; }
"""


def generate_pdf(meeting_data: dict) -> bytes:
    title = _esc(meeting_data.get("meeting_title") or "Untitled Meeting")
    created_at = _format_date(meeting_data.get("created_at"))

    highlights = meeting_data.get("highlights") or []
    highlights_html = "".join(f"<li>{_esc(h)}</li>" for h in highlights) or \
        "<li>No key points detected.</li>"

    action_items = meeting_data.get("action_items") or []
    if action_items:
        rows_html = "".join(
            f"<tr><td>{_esc(item.get('text'))}</td>"
            f"<td>{_esc(item.get('assigned_to') or 'Unassigned')}</td>"
            f"<td>{_esc(item.get('due_date') or 'No due date')}</td></tr>"
            for item in action_items
        )
    else:
        rows_html = "<tr><td colspan='3'>No action items detected.</td></tr>"

    chapters = meeting_data.get("chapters") or []
    if chapters:
        chapters_html = "".join(
            f"<div class='chapter'><h3>Chapter {i}: {_esc(ch.get('title') or f'Topic {i}')}</h3>"
            f"<p>{_esc(ch.get('summary', ''))}</p></div>"
            for i, ch in enumerate(chapters, start=1)
        )
    else:
        chapters_html = "<p>No chapters available.</p>"

    html = f"""
    <html>
    <head><style>{_CSS}</style></head>
    <body>
        <h1>Meeting Minutes</h1>
        <h2 class="subtitle">{title}</h2>

        <table class="meta">
            <tr><td>Date</td><td>{created_at}</td></tr>
            <tr><td>Generated by</td><td>AI Meeting Minutes Generator</td></tr>
        </table>

        <h2>Highlights</h2>
        <h3>Key Points</h3>
        <ul class="bullets">{highlights_html}</ul>

        <h3>Action Items</h3>
        <table class="actions">
            <tr><th>Task</th><th>Assigned To</th><th>Due Date</th></tr>
            {rows_html}
        </table>

        <h2>Detailed Minutes</h2>
        {chapters_html}

        <div class="footer">Generated automatically by AI Meeting Minutes Generator — {created_at}</div>
    </body>
    </html>
    """

    return HTML(string=html).write_pdf()
